version: "3.8"
services:
  frontend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
  backend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"  